name: Build and Push Docker Images

on:
    push:
        branches: [main, master]
        tags: ["v*"]
    pull_request:
        branches: [main, master]

env:
    REGISTRY: docker.io
    NAMESPACE: statewide
    IMAGE_NAME: nscr

jobs:
    build-and-push:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Log in to Docker Hub
              if: github.event_name != 'pull_request'
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Extract metadata
              id: meta
              uses: docker/metadata-action@v5
              with:
                  images: |
                      ${{ env.REGISTRY }}/${{ env.NAMESPACE }}/${{ env.IMAGE_NAME }}
                      ${{ env.REGISTRY }}/${{ env.NAMESPACE }}/${{ env.IMAGE_NAME }}-semeru
                  tags: |
                      type=ref,event=branch
                      type=ref,event=pr
                      type=semver,pattern={{version}}
                      type=semver,pattern={{major}}.{{minor}}
                      type=semver,pattern={{major}}
                      type=raw,value=latest,enable={{is_default_branch}}

            - name: Build and push default JDK image
              if: github.event_name != 'pull_request'
              uses: docker/build-push-action@v5
              with:
                  context: .
                  target: default
                  push: true
                  tags: ${{ steps.meta.outputs.tags }}
                  labels: ${{ steps.meta.outputs.labels }}
                  cache-from: type=gha
                  cache-to: type=gha,mode=max

            - name: Build and push Semeru image
              if: github.event_name != 'pull_request'
              uses: docker/build-push-action@v5
              with:
                  context: .
                  target: semeru
                  push: true
                  tags: ${{ steps.meta.outputs.tags }}
                  labels: ${{ steps.meta.outputs.labels }}
                  cache-from: type=gha
                  cache-to: type=gha,mode=max

            - name: Build images (no push) for PR
              if: github.event_name == 'pull_request'
              uses: docker/build-push-action@v5
              with:
                  context: .
                  target: default
                  push: false
                  tags: ${{ env.REGISTRY }}/${{ env.NAMESPACE }}/${{ env.IMAGE_NAME }}:pr-${{ github.event.number }}
                  cache-from: type=gha
                  cache-to: type=gha,mode=max

            - name: Build Semeru image (no push) for PR
              if: github.event_name == 'pull_request'
              uses: docker/build-push-action@v5
              with:
                  context: .
                  target: semeru
                  push: false
                  tags: ${{ env.REGISTRY }}/${{ env.NAMESPACE }}/${{ env.IMAGE_NAME }}-semeru:pr-${{ github.event.number }}
                  cache-from: type=gha
                  cache-to: type=gha,mode=max
